// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAECKyxXcDU6GPMtZIkoGOZmzg82nVWQg',
    appId: '1:181596192993:web:b0cd8062b05d1732f037a0',
    messagingSenderId: '181596192993',
    projectId: 'pioneers-chat-app',
    authDomain: 'pioneers-chat-app.firebaseapp.com',
    storageBucket: 'pioneers-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcalLQqRGqBY2OhjdN0DRTYDQflThjuUc',
    appId: '1:181596192993:android:69ebdfe3c11b0639f037a0',
    messagingSenderId: '181596192993',
    projectId: 'pioneers-chat-app',
    storageBucket: 'pioneers-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMrrP804SpvSrAX55u405gvMmsl7ZTOQM',
    appId: '1:181596192993:ios:942201968c172283f037a0',
    messagingSenderId: '181596192993',
    projectId: 'pioneers-chat-app',
    storageBucket: 'pioneers-chat-app.appspot.com',
    iosClientId: '181596192993-7dko7l4lbk67dk06drkr5ihctp21dk83.apps.googleusercontent.com',
    iosBundleId: 'com.example.pioneersChatApp',
  );
}
